#!/usr/bin/python3

"""Randomly choose terminal background color. Caller may provide seed."""

# See https://github.com/sos4nt/dynamic-colors/blob/master/bin/dynamic-colors

import random
import sys

import misc

COLORS = (
    """
    rgb:ff/ee/ee
    rgb:ee/ff/ee
    rgb:ee/ee/ff
    rgb:ff/ff/ee
    rgb:ff/ee/ff
    rgb:ee/ff/ff

    rgb:ff/dd/dd
    rgb:dd/ff/dd
    rgb:dd/dd/ff
    rgb:ff/ff/dd
    rgb:ff/dd/ff
    rgb:dd/ff/ff
    """
    ).split()


def parse_args():
    """Parse arguments."""
    p = misc.get_basic_parser(description=__doc__)
    p.add('-c', '--color', default='random',
          help='set background color')
    p.add('-s', '--seed')
    args = p.parse_args()
    return args


def main():
    """Main."""
    args = parse_args()
    if args.seed:
        random.seed(args.seed)

    color = random.choice(COLORS)
    sys.stdout.write(misc.set_term_bg(color))


if __name__ == '__main__':
    sys.exit(main())
